version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadba2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_DATABASE: DEATHBIKES
    volumes:
      - mariadb_dataa2:/var/lib/mysql:rw
      - ./Bicicletas.sql:/docker-entrypoint-initdb.d/Bicicletas.sql:rw

    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina2
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7002:80
    depends_on:
      - mariadb
  python:
    build: .
    container_name: pythona2
    environment:
      DB_USERNAME: user
      DB_PASSWORD: user
      DB_DATABASE: DEATHBIKE
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      PYTHONUNBUFFERED: 1
      SECRET_KEY: 'you-will-never-guess'
      DEBUG: "False"


    depends_on:
        - mariadb

        #Meter APACHE
  apache:
    build: ./Apache
    ports:
      - 6002:80
  
volumes:
  mariadb_dataa2: