version: '3'
services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadba2
    restart: always
    environment:
      MARIADB_DATABASE: DEATHBIKES
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      #MARIADB_ROOT_PASSWORD: example
      #MARIADB_USER: user
      #MARIADB_PASSWORD: user
      
    volumes:
      - mariadb_dataa2:/var/lib/mysql #:rw
      - ./Bicicletas.sql:/docker-entrypoint-initdb.d/Bicicletas.sql #:rw
    #user: mysql
    secrets:
      - db_root_password

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina2
    restart: always
    environment:
      PMA_ARBITRARY:
      PMA_HOST: mariadb
    ports:
      - 7002:80
    links:
      - mariadb
    depends_on:
      - mariadb
  python:
    build: .
    container_name: pythona2
    #environment:
    #  DB_USERNAME: user
    #  DB_PASSWORD: user
    #  DB_DATABASE: DEATHBIKES
    #  DB_HOST: mariadb
    #  DB_PORT: 3306
    #  PORT: 8080
    #  HOST: 0.0.0.0
    #  PYTHONUNBUFFERED: 1
    #  SECRET_KEY: 'you-will-never-guess'
    #  DEBUG: "False"
    depends_on:
        - mariadb
    env_file: .env
    environment:
      DB_PORT: 3306
      DB_HOST: mariadb
      DB_DATABASE: DEATHBIKES
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      WTF_CSRF_SECRET_KEY: ${WTF_CSRF_SECRET_KEY}       
      HOST: "0.0.0.0"
      PORT: 8080
    volumes:
      - ./logapi/:/app/logs
        #Meter APACHE
#  apache:
 #   build: ./Apache
  #  ports:
   #   - 6002:80
  apache-waf:
    container_name: apachea2
    build: ./Apache/ #./waf/ en un futuro
    ports:
      - 6012:443
      - 6002:80
    depends_on:
      - python
    links:
      - python
    volumes:
      #- ./apache/static:/var/www/html # en el futuro se quita
      - ./logwaf:/var/log/apache2
  
volumes:
  mariadb_dataa2:


secrets:
  db_root_user:
    file: ./secretos/db_root_user.txt
  db_root_password:
    file: ./secretos/db_root_password.txt
  db_user_username:
    file: ./secretos/db_user_username.txt
  db_user_password:
    file: ./secretos/db_user_password.txt
      
