version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_DATABASE: DEATHBIKES
    volumes:
      - ./mariadb_data:/var/lib/mysql:rw
      - ./Bicicletas.sql:/docker-entrypoint-initdb.d/Bicicletas.sql:r

    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: user
      DB_PASSWORD: user
      DB_DATABASE: DEATHBIKES
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      PYTHONUNBUFFERED: 1
    ports:
      - 9094:8080
    depends_on:
        - mariadb

        #Meter APACHE
  apache:
    build: ./Apache
    ports:
      - 9095:80
